package offensive

import (
	"context"
	"fmt"
	"log"
	"os/exec"
	"strings"
)

// ReconEngine handles target enumeration using underlying OS tools explicitly.
type ReconEngine struct {
	roe *RulesOfEngagement
}

func NewReconEngine(roe *RulesOfEngagement) *ReconEngine {
	return &ReconEngine{roe: roe}
}

// TargetProfile contains parsed data generated by a Recon operation.
type TargetProfile struct {
	IP        string
	OpenPorts []string
	RawOutput string
}

// Scan uses a basic wrapper around nmap to detect open TCP ports rapidly.
// Requires nmap installed in the operating system environment.
func (r *ReconEngine) Scan(ctx context.Context, targetIP string) (*TargetProfile, error) {
	if err := r.roe.IsTargetAllowed(targetIP); err != nil {
		return nil, fmt.Errorf("reconnaissance aborted: %w", err)
	}

	log.Printf("[RECON] Booting active footprinting sequence against %s (Authorized by RoE)", targetIP)

	// -Pn (No ping), -T4 (Aggressive), -F (Fast/100 ports), --open (Only open ports)
	cmd := exec.CommandContext(ctx, "nmap", "-Pn", "-T4", "-F", "--open", targetIP)
	output, err := cmd.CombinedOutput()

	if err != nil {
		// Log but don't strictly return err if nmap at least ran but had non-zero exit
		log.Printf("[RECON-WARN] Nmap returned error code (Host down?): %v\nOutput:%s", err, string(output))
	}

	profile := &TargetProfile{
		IP:        targetIP,
		OpenPorts: parseNmapPorts(string(output)),
		RawOutput: string(output), // Retained for LLM processing
	}

	if len(profile.OpenPorts) == 0 {
		return profile, fmt.Errorf("no open ports discovered on target %s", targetIP)
	}

	log.Printf("[RECON] Found %d open ports on %s", len(profile.OpenPorts), targetIP)
	return profile, nil
}

// parseNmapPorts is a naive regex-free parser pulling out "PORT" lines
// Example line: "80/tcp open http"
func parseNmapPorts(output string) []string {
	var ports []string
	lines := strings.Split(output, "\n")
	scanStarted := false

	for _, line := range lines {
		if strings.HasPrefix(line, "PORT") && strings.Contains(line, "STATE") {
			scanStarted = true
			continue
		}
		if scanStarted {
			if strings.TrimSpace(line) == "" {
				continue // Done scanning ports block
			}
			parts := strings.Fields(line)
			if len(parts) >= 2 && parts[1] == "open" {
				ports = append(ports, parts[0]) // Append e.g., "80/tcp"
			}
		}
	}
	return ports
}
